"""
This module was autogenerated by gale.
"""
import settings
from src.Racexstreet import Racexstreet

if __name__ == "__main__":
    game = Racexstreet(
        "Racexstreet",
        settings.WINDOW_WIDTH,
        settings.WINDOW_HEIGHT,
        settings.VIRTUAL_WIDTH,
        settings.VIRTUAL_HEIGHT,
    )
    game.exec()
